name: Sincronizar Álbumes Diariamente

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sincronizar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar script de sincronización
      run: node sync_blog.js

